const DB_PRODUCTS = {
  pizza: [
    {
      id: 1,
      img: 'pizza1',
      category: 'pizza',
      type: 'spicy',
      name: 'Pizza Calabria',
      ingredients: [
        'Tomato Sauce',
        'Mozzarella',
        'Mascarpone',
        'Nduja Spicy Sausage',
        'Rocket',
      ],
      composition: { isPerpper: true, isVegan: false },
      price: '13.99',
      info: {
        calories: 163,
        totalFat: 4.7,
        carbohydrates: 20.4,
        protein: 7.6,
      },
    },
    {
      id: 2,
      img: 'pizza2',
      category: 'pizza',
      type: 'spicy',
      name: 'Pizza Pepperoni',
      ingredients: ['Tomato Sauce', 'Mozzarella', 'Double Pepperoni'],
      composition: { isPerpper: true, isVegan: false },
      price: '16.49',
      info: {
        calories: 163,
        totalFat: 4.7,
        carbohydrates: 20.4,
        protein: 7.6,
      },
    },
    {
      id: 3,
      img: 'pizza3',
      category: 'pizza',
      type: 'spicy',
      name: 'Pizza Regina',
      ingredients: [
        'Tomato Sauce',
        'Mozzarella',
        'Parmesan',
        'Ham',
        'Mushrooms',
        'Black Olives',
      ],
      composition: { isPerpper: true, isVegan: true },
      price: '7.71',
      info: {
        calories: 163,
        totalFat: 4.7,
        carbohydrates: 20.4,
        protein: 7.6,
      },
    },
    {
      id: 4,
      img: 'pizza4',
      category: 'pizza',
      type: 'vegetarian',
      name: 'Pizza Bianca',
      ingredients: [
        'Garlic Flatbread with Mozzarella',
        'Parmesan',
        'Garlic',
        'Rosemary',
      ],
      composition: { isPerpper: false, isVegan: true },
      price: '13.71',
      info: {
        calories: 163,
        totalFat: 4.7,
        carbohydrates: 20.4,
        protein: 7.6,
      },
    },
    {
      id: 5,
      img: 'pizza5',
      category: 'pizza',
      type: 'vegetarian',
      name: 'Pizza Funghi',
      ingredients: ['Tomato Sauce', 'Mozzarella', 'Mushrooms', 'Thyme'],
      composition: { isPerpper: false, isVegan: true },
      price: '7.71',
      info: {
        calories: 163,
        totalFat: 4.7,
        carbohydrates: 20.4,
        protein: 8.14,
      },
    },
    {
      id: 6,
      img: 'pizza6',
      category: 'pizza',
      type: 'vegetarian',
      name: 'Pizza Margherita',
      ingredients: ['Tomato Sauce', 'Mozzarella', 'Basil'],
      composition: { isPerpper: false, isVegan: true },
      price: '7.71',
      info: {
        calories: 163,
        totalFat: 4.7,
        carbohydrates: 20.4,
        protein: 11.67,
      },
    },
    {
      id: 7,
      img: 'pizza7',
      category: 'pizza',
      type: 'vegetarian',
      name: 'Pizza Regina',
      ingredients: [
        'Tomato Sauce',
        'Mozzarella',
        'Parmesan',
        'Ham',
        'Mushrooms',
        'Black Olives',
      ],
      composition: { isPerpper: true, isVegan: true },
      price: '17.71',
      info: {
        calories: 163,
        totalFat: 4.7,
        carbohydrates: 20.4,
        protein: 7.6,
      },
    },
    {
      id: 8,
      img: 'pizza8',
      category: 'pizza',
      type: 'mushrooms',
      name: 'Pizza Carne',
      ingredients: [
        'Tomato Sauce',
        'Mozzarella',
        'Onions',
        'Chicken',
        'Beef',
        'Pepperoni',
        'Rosemary',
      ],
      composition: { isPerpper: false, isVegan: true },
      price: '17.71',
      info: {
        calories: 163,
        totalFat: 4.7,
        carbohydrates: 20.4,
        protein: 7.6,
      },
    },
    {
      id: 9,
      img: 'pizza9',
      category: 'pizza',
      type: 'mushrooms',
      name: 'Pizza Regina',
      ingredients: [
        'Tomato Sauce',
        'Mozzarella',
        'Parmesan',
        'Ham',
        'Mushrooms',
        'Black Olives',
      ],
      composition: { isPerpper: true, isVegan: true },
      price: '17.71',
      info: {
        calories: 163,
        totalFat: 4.7,
        carbohydrates: 20.4,
        protein: 7.6,
      },
    },
    {
      id: 10,
      img: 'pizza10',
      category: 'pizza',
      type: 'meat',
      name: 'Pizza Calabria',
      ingredients: [
        'Tomato Sauce',
        'Mozzarella',
        'Mascarpone',
        'Nduja Spicy Sausage',
        'Rocket',
      ],
      composition: { isPerpper: true, isVegan: false },
      price: '27.75',
      info: {
        calories: 163,
        totalFat: 4.7,
        carbohydrates: 20.4,
        protein: 7.6,
      },
    },
    {
      id: 11,
      img: 'pizza11',
      category: 'pizza',
      type: 'meat',
      name: 'Pizza Regina',
      ingredients: [
        'Tomato Sauce',
        'Mozzarella',
        'Mascarpone',
        'Nduja Spicy Sausage',
        'Rocket',
      ],
      composition: { isPerpper: true, isVegan: true },
      price: '15.71',
      info: {
        calories: 163,
        totalFat: 4.7,
        carbohydrates: 20.4,
        protein: 7.6,
      },
    },
    {
      id: 12,
      img: 'pizza12',
      category: 'pizza',
      type: 'seafood',
      name: 'Pizza Formaggi',
      ingredients: [
        'Tomato Sauce',
        'Mozzarella',
        'Mascarpone',
        'Parmesan',
        'Mascarpone',
        'Gorgonzola',
      ],
      composition: { isPerpper: false, isVegan: false },
      price: '15.71',
      info: {
        calories: 163,
        totalFat: 4.7,
        carbohydrates: 20.4,
        protein: 6.16,
      },
    },
    {
      id: 13,
      img: 'pizza11',
      category: 'pizza',
      type: 'seafood',
      name: 'Pizza Milano',
      ingredients: [
        'Tomato Sauce',
        'Mozzarella',
        'Mascarpone',
        'Nduja Spicy Sausage',
        'Rocket',
      ],
      composition: { isPerpper: false, isVegan: false },
      price: '13.21',
      info: {
        calories: 163,
        totalFat: 4.7,
        carbohydrates: 20.4,
        protein: 8.3,
      },
    },
    {
      id: 14,
      img: 'pizza11',
      category: 'pizza',
      type: 'seafood',
      name: 'Pizza Vesuvio',
      ingredients: [
        'Tomato Sauce',
        'Mozzarella',
        'Pepperoni',
        'Mixed Peppers',
        'Green Chillies',
        'Cracked Chillies',
      ],
      composition: { isPerpper: false, isVegan: false },
      price: '11.39',
      info: {
        calories: 163,
        totalFat: 4.7,
        carbohydrates: 20.4,
        protein: 17.6,
      },
    },
  ],
  Burgers: [
    {
      id: 15,
      img: 'burger1',
      category: 'burgers',
      type: 'spice',
      name: 'California burger',
      ingredients: [
        'A hamburger served with chicken',
        'lettuce',
        'tomato',
        'and onion',
      ],
      composition: { isPerpper: true, isVegan: false },
      price: '17.39',
    },
    {
      id: 16,
      img: 'burger2',
      category: 'burgers',
      type: 'spice',
      name: 'Chili burger',
      ingredients: [
        'A hamburger served with chicken',
        'lettuce',
        'tomato',
        'and onion',
      ],
      composition: { isPerpper: true, isVegan: false },
      price: '17.39',
    },
    {
      id: 17,
      img: 'burger3',
      category: 'burgers',
      type: 'spice',
      name: 'Double slugburger',
      ingredients: [
        'A hamburger served with chicken',
        'lettuce',
        'tomato',
        'and onion',
      ],
      composition: { isPerpper: true, isVegan: false },
      price: '7.9',
    },

    {
      id: 18,
      img: 'burger4',
      category: 'burgers',
      type: 'meat',
      name: 'Buffalo burger',
      ingredients: ['Buffalo burgers have less cholesterol and less fat'],
      composition: { isPerpper: false, isVegan: false },
      price: '27.39',
    },
    {
      id: 19,
      img: 'burger5',
      category: 'burgers',
      type: 'meat',
      name: 'Double Buffalo burger',
      ingredients: ['Buffalo burgers have less cholesterol and less fat'],
      composition: { isPerpper: false, isVegan: false },
      price: '12.49',
    },
    {
      id: 20,
      img: 'burger6',
      category: 'burgers',
      type: 'meat',
      name: ' Double slugburger',
      ingredients: [
        'Served on a bun with mustard, pickles, onion, and French fries',
      ],
      composition: { isPerpper: true, isVegan: false },
      price: '23.39',
    },

    {
      id: 21,
      img: 'burger7',
      category: 'burgers',
      type: 'fish',
      name: 'Bacon cheeseburger',
      ingredients: ['Hamburger with bacon and cheese'],
      composition: { isPerpper: false, isVegan: false },
      price: '25.49',
    },
    {
      id: 22,
      img: 'burger8',
      category: 'burgers',
      type: 'fish',
      name: 'Slugburger',
      ingredients: [
        'Served on a bun with mustard, pickles, onion, and French fries',
      ],
      composition: { isPerpper: false, isVegan: false },
      price: '24.29',
    },

    //Chicken
    {
      id: 23,
      img: 'burger9',
      category: 'burgers',
      type: 'chicken',
      name: 'California burger',
      ingredients: [
        'A hamburger served with chicken, lettuce, tomato, and onion',
      ],
      composition: { isPerpper: true, isVegan: false },
      price: '18.49',
    },
    {
      id: 24,
      img: 'burger10',
      category: 'burgers',
      type: 'chicken',
      name: 'Chili burger',
      ingredients: [
        'A hamburger served with chicken, chili, lettuce, tomato, and onion',
      ],
      composition: { isPerpper: true, isVegan: false },
      price: '24.29',
    },
    {
      id: 25,
      img: 'burger11',
      category: 'burgers',
      type: 'chicken',
      name: 'Double Buffalo burger',
      ingredients: ['Buffalo burgers have less cholesterol and less fat'],
      composition: { isPerpper: false, isVegan: false },
      price: '24.29',
    },
  ],

  sushi: [
    {
      id: 26,
      img: 'sushi1',
      category: 'sushi',
      name: 'Dynamite Roll',
      ingredients: ['Shrimp tempura, yellowtail, bean sprouts, carrots'],
      composition: { isPerpper: false, isVegan: false },
      price: '24.29',
    },
    {
      id: 27,
      img: 'sushi2',
      category: 'sushi',
      name: 'Crunch Roll',
      ingredients: ['Spicy tuna, crispy seaweed, tempura'],
      composition: { isPerpper: false, isVegan: false },
      price: '24.29',
    },
    {
      id: 28,
      img: 'sushi3',
      category: 'sushi',
      name: 'Dragon Roll',
      ingredients: ['Eel, crab, cucumber / avocado outside, eel sauce'],
      composition: { isPerpper: false, isVegan: false },
      price: '24.29',
    },
    {
      id: 29,
      img: 'sushi4',
      category: 'sushi',
      name: 'Dynamite Roll',
      ingredients: ['Shrimp tempura, yellowtail, bean sprouts, carrots'],
      composition: { isPerpper: false, isVegan: false },
      price: '4.29',
    },
    {
      id: 30,
      img: 'sushi5',
      category: 'sushi',
      name: 'Rainbow Roll',
      ingredients: ['Fish cake/imitation crab, avocado, cucumber, tuna'],
      composition: { isPerpper: false, isVegan: false },
      price: '4.93',
    },
    {
      id: 31,
      img: 'sushi6',
      category: 'sushi',
      name: 'Shrimp Tempura Roll',
      ingredients: ['Shrimp tempura, avocado, tempura flakes, eel sauce'],
      composition: { isPerpper: false, isVegan: false },
      price: '14.2',
    },
    {
      id: 32,
      img: 'sushi7',
      category: 'sushi',
      name: 'Spicy Tuna Roll',
      ingredients: ['Tuna, mayo, chili sauce, avocado, carrot'],
      composition: { isPerpper: false, isVegan: false },
      price: '8.29',
    },
    {
      id: 33,
      img: 'sushi8',
      category: 'sushi',
      name: 'Spider Roll',
      ingredients: ['Soft-shell crab tempura, cucumber, avocado, spicy mayo'],
      composition: { isPerpper: false, isVegan: false },
      price: '4.92',
    },
    {
      id: 34,
      img: 'sushi9',
      category: 'sushi',
      name: 'Tekkamaki',
      ingredients: ['One or more of the parts is deep-fried in a light batter'],
      composition: { isPerpper: false, isVegan: false },
      price: '8.19',
    },
    {
      id: 35,
      img: 'sushi10',
      category: 'sushi',
      name: 'Vegetable Roll',
      ingredients: ['Cucumber, fresh carrot, scallion, avocado'],
      composition: { isPerpper: false, isVegan: false },
      price: '4.29',
    },
  ],

  noodles: [
    {
      id: 36,
      img: 'noodles1',
      category: 'noodles',
      name: 'Chicken Chow Mein',
      ingredients: ['Chicken, bok choy, celery, red bell pepper, oyster sauce'],
      composition: { isPerpper: false, isVegan: false },
      price: '7.29',
    },
    {
      id: 37,
      img: 'noodles2',
      category: 'noodles',
      name: 'Japanese udon noodles',
      ingredients: ['Japanese udon noodles with salmon fish'],
      composition: { isPerpper: false, isVegan: false },
      price: '14.39',
    },
    {
      id: 38,
      img: 'noodles3',
      category: 'noodles',
      name: 'Shanghai Stir-Fry Noodles',
      ingredients: ['Beef meat, celery, red bell pepper, oyster sauce'],
      composition: { isPerpper: false, isVegan: false },
      price: '2.87',
    },
    {
      id: 39,
      img: 'noodles4',
      category: 'noodles',
      name: 'Sichuan Noodles',
      ingredients: ['Combines chicken, mushrooms, and a spicy sauce'],
      composition: { isPerpper: false, isVegan: false },
      price: '5.29',
    },
    {
      id: 40,
      img: 'noodles5',
      category: 'noodles',
      name: 'Singapore Noodles',
      ingredients: ['Combines chicken, shrimp, and a spicy sauce'],
      composition: { isPerpper: false, isVegan: false },
      price: '4.29',
    },
  ],

  steaks: [
    {
      id: 41,
      img: 'steaks1',
      category: 'steaks',
      name: 'American Wagyu Eye of Rib',
      ingredients: ['American Wagyu Eye of Rib, Snake River Farm, ID'],
      composition: { isPerpper: false, isVegan: false },
      price: '27.29',
    },
    {
      id: 42,
      img: 'steaks2',
      category: 'steaks',
      name: 'Australian Wagyu',
      ingredients: ['Australian Wagyu New York, Queensland AUS'],
      composition: { isPerpper: false, isVegan: false },
      price: '43.39',
    },
    {
      id: 43,
      img: 'steaks3',
      category: 'steaks',
      name: 'Crispy Skin Duck',
      ingredients: [
        'Crispy Skin Duck, Roasted Persimmon, Chiogga Beet, Confit Dumplings',
      ],
      composition: { isPerpper: false, isVegan: false },
      price: '7.29',
    },
    {
      id: 44,
      img: 'steaks4',
      category: 'steaks',
      name: 'Filet Mignon',
      ingredients: ['Filet Mignon, Double R Ranch, WA'],
      composition: { isPerpper: false, isVegan: false },
      price: '11.57',
    },
    {
      id: 45,
      img: 'steaks5',
      category: 'steaks',
      name: 'Petite Filet Mignon',
      ingredients: ['Petite Filet Mignon, Double R Ranch, WA'],
      composition: { isPerpper: false, isVegan: false },
      price: '7.29',
    },
    {
      id: 46,
      img: 'steaks6',
      category: 'steaks',
      name: 'Salmon Steak',
      ingredients: ['Petite Salmon Steak & Steamed Maine Lobster'],
      composition: { isPerpper: false, isVegan: false },
      price: '31.69',
    },
    {
      id: 47,
      img: 'steaks7',
      category: 'steaks',
      name: 'Taste of Wagyu',
      ingredients: ['Taste of Wagyu – New York – Picanha – Japanese'],
      composition: { isPerpper: false, isVegan: false },
      price: '13.82',
    },
    {
      id: 48,
      img: 'steaks8',
      category: 'steaks',
      name: 'Wagyu Filet',
      ingredients: ['Wagyu Filet, Snake River Farms'],
      composition: { isPerpper: false, isVegan: false },
      price: '23.59',
    },
    {
      id: 49,
      img: 'steaks9',
      category: 'steaks',
      name: 'Wagyu Rib Cap',
      ingredients: ['American Wagyu Rib Cap, Snake River Farm, ID'],
      composition: { isPerpper: false, isVegan: false },
      price: '13.98',
    },
    {
      id: 50,
      img: 'steaks10',
      category: 'steaks',
      name: 'Wagyu Skirt Steak',
      ingredients: ['American Wagyu Skirt Steak, Snake River Farm, ID'],
      composition: { isPerpper: false, isVegan: false },
      price: '67.29',
    },
  ],

  desserts: [
    {
      id: 51,
      img: 'desserts1',
      category: 'desserts',
      name: 'Amandine',
      ingredients: ['Flour, full-fat milk, egg yolks, whipping cream'],
      composition: { isPerpper: false, isVegan: false },
      price: '7.29',
    },
    {
      id: 52,
      img: 'desserts2',
      category: 'desserts',
      name: 'Cheesecake',
      ingredients: ['Sour cream, farmer’s cheese, cream cheese'],
      composition: { isPerpper: false, isVegan: false },
      price: '6.19',
    },
    {
      id: 53,
      img: 'desserts3',
      category: 'desserts',
      name: 'Chocolate cake',
      ingredients: ['Flour, full-fat milk, cocoa, egg yolks, whipping cream'],
      composition: { isPerpper: false, isVegan: false },
      price: '7.29',
    },
    {
      id: 54,
      img: 'desserts4',
      category: 'desserts',
      name: 'Chocolate ice cream',
      ingredients: ['Full-fat milk, cocoa, egg yolks, whipping cream'],
      composition: { isPerpper: false, isVegan: false },
      price: '8.88',
    },
    {
      id: 55,
      img: 'desserts5',
      category: 'desserts',
      name: 'Fondant',
      ingredients: ['Flour, cocoa powder, egg yolks, whipping cream'],
      composition: { isPerpper: false, isVegan: false },
      price: '1.79',
    },
    {
      id: 56,
      img: 'desserts6',
      category: 'desserts',
      name: 'Tiramisu',
      ingredients: ['Biscotti savoiardi, espresso, egg yolks, whole milk'],
      composition: { isPerpper: false, isVegan: false },
      price: '4.21',
    },
  ],

  drinks: [
    {
      id: 57,
      img: 'drinks1',
      category: 'drinks',
      name: 'Melon smoothie',
      ingredients: ['Melon, almond milk, chia seeds'],
      composition: { isPerpper: false, isVegan: false },
      price: '4.21',
    },
    {
      id: 58,
      img: 'drinks2',
      category: 'drinks',
      name: 'Peach smoothie',
      ingredients: ['Peach, almond milk, chia seeds'],
      composition: { isPerpper: false, isVegan: false },
      price: '2.33',
    },
    {
      id: 59,
      img: 'drinks3',
      category: 'drinks',
      name: 'Raspberry smoothie',
      ingredients: ['Raspberry, almond milk, chia seeds'],
      composition: { isPerpper: false, isVegan: false },
      price: '7.33',
    },
    {
      id: 60,
      img: 'drinks4',
      category: 'drinks',
      name: 'Strawberry smoothie',
      ingredients: ['Strawberry, almond milk, chia seeds'],
      composition: { isPerpper: false, isVegan: false },
      price: '8.21',
    },
    {
      id: 61,
      img: 'drinks5',
      category: 'drinks',
      name: 'Watermelon smoothie',
      ingredients: ['Watermelon, almond milk, chia seeds'],
      composition: { isPerpper: false, isVegan: false },
      price: '5.38',
    },
    {
      id: 62,
      img: 'drinks6',
      category: 'drinks',
      name: 'Strawberry smoothie',
      ingredients: ['Strawberry, almond milk, chia seeds'],
      composition: { isPerpper: false, isVegan: false },
      price: '5.38',
    },
    {
      id: 63,
      img: 'drinks7',
      category: 'drinks',
      name: 'Watermelon smoothie',
      ingredients: ['Watermelon, almond milk, chia seeds'],
      composition: { isPerpper: false, isVegan: false },
      price: '5.38',
    },
  ],
};

export default DB_PRODUCTS